In [184]:
import pandas as pd
import matplotlib.pyplot as plt

In [185]:
df = pd.read_csv("clean_data_after_eda.csv",index_col = False)

In [186]:
df.head()

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,...,mean_3m_price_off_peak_var,mean_3m_price_peak_var,mean_3m_price_mid_peak_var,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn
0,0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,...,0.131756,0.092638,0.036909,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1
1,1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,...,0.147600,0.000000,0.000000,44.444710,0.000000,0.000000,44.592310,0.000000,0.000000,0
2,2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,...,0.167798,0.088409,0.000000,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0
3,3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,...,0.148586,0.000000,0.000000,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0
4,4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,...,0.119906,0.101673,0.073719,40.728885,24.437330,16.291555,40.848791,24.539003,16.365274,0

In [187]:
#df = df.drop(columns=['id','Unnamed: 0'])

In [188]:
df.columns

Index(['Unnamed: 0', 'id', 'channel_sales', 'cons_12m', 'cons_gas_12m',
       'cons_last_month', 'date_activ', 'date_end', 'date_modif_prod',
       'date_renewal', 'forecast_cons_12m', 'forecast_cons_year',
       'forecast_discount_energy', 'forecast_meter_rent_12m',
       'forecast_price_energy_off_peak', 'forecast_price_energy_peak',
       'forecast_price_pow_off_peak', 'has_gas', 'imp_cons',
       'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'num_years_antig', 'origin_up', 'pow_max',
       'mean_year_price_off_peak_var', 'mean_year_price_peak_var',
       'mean_year_price_mid_peak_var', 'mean_year_price_off_peak_fix',
       'mean_year_price_peak_fix', 'mean_year_price_mid_peak_fix',
       'mean_year_price_off_peak', 'mean_year_price_peak',
       'mean_year_price_mid_peak', 'mean_6m_price_off_peak_var',
       'mean_6m_price_peak_var', 'mean_6m_price_mid_peak_var',
       'mean_6m_price_off_peak_fix', 'mean_6m_price_peak_fix',
       'mean_6m_price_mid_peak_fix', 'mean_6m_price_off_peak',
       'mean_6m_price_peak', 'mean_6m_price_mid_peak',
       'mean_3m_price_off_peak_var', 'mean_3m_price_peak_var',
       'mean_3m_price_mid_peak_var', 'mean_3m_price_off_peak_fix',
       'mean_3m_price_peak_fix', 'mean_3m_price_mid_peak_fix',
       'mean_3m_price_off_peak', 'mean_3m_price_peak',
       'mean_3m_price_mid_peak', 'churn'],
      dtype='object')

In [189]:
df.describe()

,Unnamed: 0,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,mean_3m_price_off_peak_var,mean_3m_price_peak_var,mean_3m_price_mid_peak_var,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn
count,14605.000000,1.460500e+04,1.460500e+04,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,...,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000,14605.000000
mean,7302.000000,1.592303e+05,2.809108e+04,16091.371448,1868.638618,1399.858747,0.966450,63.090448,0.137282,0.050488,...,0.139312,0.051310,0.028568,43.058161,9.483665,6.115566,43.197473,9.534975,6.144134,0.097159
std,4216.244676,5.734836e+05,1.629786e+05,64366.262314,2387.651549,3247.876793,5.108355,66.166636,0.024623,0.049037,...,0.024318,0.049501,0.036376,4.668200,12.139506,7.830408,4.683855,12.179014,7.866460,0.296184
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3651.000000,5.674000e+03,0.000000e+00,0.000000,494.980000,0.000000,0.000000,16.180000,0.116340,0.000000,...,0.119405,0.000000,0.000000,40.728885,0.000000,0.000000,40.848595,0.000000,0.000000,0.000000
50%,7302.000000,1.411600e+04,0.000000e+00,793.000000,1112.610000,314.000000,0.000000,18.800000,0.143166,0.084138,...,0.144757,0.084305,0.000000,44.355820,0.000000,0.000000,44.502379,0.084305,0.000000,0.000000
75%,10953.000000,4.076400e+04,0.000000e+00,3383.000000,2402.270000,1746.000000,0.000000,131.030000,0.146348,0.098837,...,0.147983,0.100491,0.073719,44.444710,24.437330,16.291555,44.592310,24.537821,16.365180,0.000000
max,14604.000000,6.207104e+06,4.154590e+06,771203.000000,82902.830000,175375.000000,30.000000,599.310000,0.273963,0.195975,...,0.276238,0.196029,0.103502,59.444710,36.490689,17.291555,59.720948,36.610036,17.382386,1.000000

In [190]:
df.head()

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,...,mean_3m_price_off_peak_var,mean_3m_price_peak_var,mean_3m_price_mid_peak_var,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn
0,0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,...,0.131756,0.092638,0.036909,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1
1,1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,...,0.147600,0.000000,0.000000,44.444710,0.000000,0.000000,44.592310,0.000000,0.000000,0
2,2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,...,0.167798,0.088409,0.000000,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0
3,3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,...,0.148586,0.000000,0.000000,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0
4,4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,...,0.119906,0.101673,0.073719,40.728885,24.437330,16.291555,40.848791,24.539003,16.365274,0

In [191]:
pd.DataFrame({'Frequency':df['channel_sales'].value_counts()})

                                  Frequency
channel_sales
foosdfpfkusacimwkcsosbicdxkicaua       6753
MISSING                                3725
lmkebamcaaclubfxadlmueccxoimlema       1843
usilxuppasemubllopkaafesmlibmsdf       1375
ewpakwlliwisiwduibdlfmalxowmwpci        893
sddiedcslfslkckwlfkdpoeeailfpeds         11
epumfxlbckeskwekxbiuasklxalciiuu          3
fixdbufsefwooaasfcxdxadsiekoceaa          2

In [192]:
#dropping MISSING values 

df = df.drop(df[df['channel_sales'] == "MISSING"].index)

In [193]:
df.isnull().sum().sum()

0

In [194]:
df["date_activ"] = pd.to_datetime(df["date_activ"], format='%Y-%m-%d')
df["date_end"] = pd.to_datetime(df["date_end"], format='%Y-%m-%d')
df["date_modif_prod"] = pd.to_datetime(df["date_modif_prod"], format='%Y-%m-%d')
df["date_renewal"] = pd.to_datetime(df["date_renewal"], format='%Y-%m-%d')

In [195]:
type(df['date_activ'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [196]:
df.dtypes

Unnamed: 0                                 int64
id                                        object
channel_sales                             object
cons_12m                                   int64
cons_gas_12m                               int64
cons_last_month                            int64
date_activ                        datetime64[ns]
date_end                          datetime64[ns]
date_modif_prod                   datetime64[ns]
date_renewal                      datetime64[ns]
forecast_cons_12m                        float64
forecast_cons_year                         int64
forecast_discount_energy                 float64
forecast_meter_rent_12m                  float64
forecast_price_energy_off_peak           float64
forecast_price_energy_peak               float64
forecast_price_pow_off_peak              float64
has_gas                                   object
imp_cons                                 float64
margin_gross_pow_ele                     float64
margin_net_pow_ele                       float64
nb_prod_act                                int64
net_margin                               float64
num_years_antig                            int64
origin_up                                 object
pow_max                                  float64
mean_year_price_off_peak_var             float64
mean_year_price_peak_var                 float64
mean_year_price_mid_peak_var             float64
mean_year_price_off_peak_fix             float64
mean_year_price_peak_fix                 float64
mean_year_price_mid_peak_fix             float64
mean_year_price_off_peak                 float64
mean_year_price_peak                     float64
mean_year_price_mid_peak                 float64
mean_6m_price_off_peak_var               float64
mean_6m_price_peak_var                   float64
mean_6m_price_mid_peak_var               float64
mean_6m_price_off_peak_fix               float64
mean_6m_price_peak_fix                   float64
mean_6m_price_mid_peak_fix               float64
mean_6m_price_off_peak                   float64
mean_6m_price_peak                       float64
mean_6m_price_mid_peak                   float64
mean_3m_price_off_peak_var               float64
mean_3m_price_peak_var                   float64
mean_3m_price_mid_peak_var               float64
mean_3m_price_off_peak_fix               float64
mean_3m_price_peak_fix                   float64
mean_3m_price_mid_peak_fix               float64
mean_3m_price_off_peak                   float64
mean_3m_price_peak                       float64
mean_3m_price_mid_peak                   float64
churn                                      int64
dtype: object

In [197]:
for i in df.columns:
    if df[i].dtype == 'object':
        print(i)

id
channel_sales
has_gas
origin_up

In [198]:
pd.DataFrame({'Frequency':df['has_gas'].value_counts()})

         Frequency
has_gas
f             8981
t             1899

In [199]:
pd.DataFrame({'Frequency':df['origin_up'].value_counts()})

                                  Frequency
origin_up
lxidpiddsbxsbosboudacockeimpuepw       6440
kamkkxfxxuwbdslkwifmmcsiusiuosws       2748
ldkssxwpmemidmecebumciepifcamkci       1641
MISSING                                  50
usapbepcfoloekilkwsdiboslwaxobdp          1

In [200]:
df = df.drop(df[df['origin_up'] == "MISSING"].index)

In [201]:
df_numerical = df.select_dtypes(include=['int64','float64'])
df_numerical

,Unnamed: 0,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,mean_3m_price_off_peak_var,mean_3m_price_peak_var,mean_3m_price_mid_peak_var,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn
0,0,0,54946,0,0.00,0,0.0,1.78,0.114481,0.098142,...,0.131756,0.092638,0.036909,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1
2,2,544,0,0,47.96,0,0.0,38.72,0.165794,0.087899,...,0.167798,0.088409,0.000000,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0
3,3,1584,0,0,240.04,0,0.0,19.83,0.146694,0.000000,...,0.148586,0.000000,0.000000,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0
5,5,8302,0,1998,796.94,1998,0.0,30.12,0.164775,0.086131,...,0.163659,0.084587,0.000000,44.266930,0.000000,0.000000,44.430589,0.084587,0.000000,1
6,6,45097,0,0,8069.28,0,0.0,0.00,0.166178,0.087538,...,0.163361,0.084305,0.000000,44.266930,0.000000,0.000000,44.430291,0.084305,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14599,14599,87146,0,11367,712.33,713,0.0,145.82,0.120372,0.103487,...,0.123388,0.105155,0.077201,40.728885,24.437330,16.291555,40.852273,24.542485,16.368756,0
14600,14600,32270,47940,0,4648.01,0,0.0,18.57,0.138305,0.000000,...,0.140172,0.000000,0.000000,44.444710,0.000000,0.000000,44.584882,0.000000,0.000000,0
14601,14601,7223,0,181,631.69,181,0.0,144.03,0.100167,0.091892,...,0.102352,0.093181,0.070990,59.173468,36.490689,8.367731,59.275820,36.583870,8.438721,1
14602,14602,1844,0,179,190.39,179,0.0,129.60,0.116900,0.100015,...,0.119906,0.101673,0.073719,40.728885,24.437330,16.291555,40.848791,24.539003,16.365274,1
14603,14603,131,0,0,19.34,0,0.0,7.18,0.145711,0.000000,...,0.147600,0.000000,0.000000,44.444710,0.000000,0.000000,44.592310,0.000000,0.000000,0

In [202]:
df.head()

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,...,mean_3m_price_off_peak_var,mean_3m_price_peak_var,mean_3m_price_mid_peak_var,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn
0,0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,...,0.131756,0.092638,0.036909,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1
2,2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,...,0.167798,0.088409,0.000000,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0
3,3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,...,0.148586,0.000000,0.000000,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0
5,5,1aa498825382410b098937d65c4ec26d,usilxuppasemubllopkaafesmlibmsdf,8302,0,1998,2011-12-09,2016-12-09,2015-11-01,2015-12-10,...,0.163659,0.084587,0.000000,44.266930,0.000000,0.000000,44.430589,0.084587,0.000000,1
6,6,7ab4bf4878d8f7661dfc20e9b8e18011,foosdfpfkusacimwkcsosbicdxkicaua,45097,0,0,2011-12-02,2016-12-02,2011-12-02,2015-12-03,...,0.163361,0.084305,0.000000,44.266930,0.000000,0.000000,44.430291,0.084305,0.000000,1

In [203]:
from sklearn.preprocessing import LabelEncoder

df_categorical = df.select_dtypes(include=['object', 'category'])

label_encoder = LabelEncoder()

for column in df_categorical.columns:
    if column != 'id':
        df[column] = label_encoder.fit_transform(df[column])

In [204]:
df

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,...,mean_3m_price_off_peak_var,mean_3m_price_peak_var,mean_3m_price_mid_peak_var,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn
0,0,24011ae4ebbe3035111d65fa7c15bc57,3,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,...,0.131756,0.092638,0.036909,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1
2,2,764c75f661154dac3a6c254cd082ea7d,3,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,...,0.167798,0.088409,0.000000,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0
3,3,bba03439a292a1e166f80264c16191cb,4,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,...,0.148586,0.000000,0.000000,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0
5,5,1aa498825382410b098937d65c4ec26d,6,8302,0,1998,2011-12-09,2016-12-09,2015-11-01,2015-12-10,...,0.163659,0.084587,0.000000,44.266930,0.000000,0.000000,44.430589,0.084587,0.000000,1
6,6,7ab4bf4878d8f7661dfc20e9b8e18011,3,45097,0,0,2011-12-02,2016-12-02,2011-12-02,2015-12-03,...,0.163361,0.084305,0.000000,44.266930,0.000000,0.000000,44.430291,0.084305,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14599,14599,c49217f16a06263e5381eaba94a67a8b,3,87146,0,11367,2013-02-08,2016-02-08,2013-02-08,2015-02-09,...,0.123388,0.105155,0.077201,40.728885,24.437330,16.291555,40.852273,24.542485,16.368756,0
14600,14600,18463073fb097fc0ac5d3e040f356987,3,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,...,0.140172,0.000000,0.000000,44.444710,0.000000,0.000000,44.584882,0.000000,0.000000,0
14601,14601,d0a6f71671571ed83b2645d23af6de00,3,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,...,0.102352,0.093181,0.070990,59.173468,36.490689,8.367731,59.275820,36.583870,8.438721,1
14602,14602,10e6828ddd62cbcf687cb74928c4c2d2,3,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,...,0.119906,0.101673,0.073719,40.728885,24.437330,16.291555,40.848791,24.539003,16.365274,1
14603,14603,1cf20fd6206d7678d5bcafd28c53b4db,3,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,...,0.147600,0.000000,0.000000,44.444710,0.000000,0.000000,44.592310,0.000000,0.000000,0

In [205]:
df['contract_duration'] = df.date_end - df.date_activ
df['next_renewal'] = df.date_renewal - df.date_activ
df['days_since_modif_prod'] = df.date_modif_prod - df.date_activ

df['contract_duration'] = df.contract_duration.dt.days
df['next_renewal'] = df.next_renewal.dt.days
df['days_since_modif_prod'] = df.days_since_modif_prod.dt.days

In [206]:
df

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,...,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn,contract_duration,next_renewal,days_since_modif_prod
0,0,24011ae4ebbe3035111d65fa7c15bc57,3,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,...,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1,1096,738,869
2,2,764c75f661154dac3a6c254cd082ea7d,3,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,...,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0,2192,1827,0
3,3,bba03439a292a1e166f80264c16191cb,4,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,...,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0,2192,1827,0
5,5,1aa498825382410b098937d65c4ec26d,6,8302,0,1998,2011-12-09,2016-12-09,2015-11-01,2015-12-10,...,44.266930,0.000000,0.000000,44.430589,0.084587,0.000000,1,1827,1462,1423
6,6,7ab4bf4878d8f7661dfc20e9b8e18011,3,45097,0,0,2011-12-02,2016-12-02,2011-12-02,2015-12-03,...,44.266930,0.000000,0.000000,44.430291,0.084305,0.000000,1,1827,1462,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14599,14599,c49217f16a06263e5381eaba94a67a8b,3,87146,0,11367,2013-02-08,2016-02-08,2013-02-08,2015-02-09,...,40.728885,24.437330,16.291555,40.852273,24.542485,16.368756,0,1095,731,0
14600,14600,18463073fb097fc0ac5d3e040f356987,3,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,...,44.444710,0.000000,0.000000,44.584882,0.000000,0.000000,0,1445,732,1079
14601,14601,d0a6f71671571ed83b2645d23af6de00,3,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,...,59.173468,36.490689,8.367731,59.275820,36.583870,8.438721,1,1461,1096,0
14602,14602,10e6828ddd62cbcf687cb74928c4c2d2,3,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,...,40.728885,24.437330,16.291555,40.848791,24.539003,16.365274,1,1460,1097,0
14603,14603,1cf20fd6206d7678d5bcafd28c53b4db,3,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,...,44.444710,0.000000,0.000000,44.592310,0.000000,0.000000,0,1461,1096,0

In [207]:
df = df.drop(columns=['date_activ','date_end','date_modif_prod','date_renewal'])

In [208]:
df

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,...,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn,contract_duration,next_renewal,days_since_modif_prod
0,0,24011ae4ebbe3035111d65fa7c15bc57,3,0,54946,0,0.00,0,0.0,1.78,...,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1,1096,738,869
2,2,764c75f661154dac3a6c254cd082ea7d,3,544,0,0,47.96,0,0.0,38.72,...,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0,2192,1827,0
3,3,bba03439a292a1e166f80264c16191cb,4,1584,0,0,240.04,0,0.0,19.83,...,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0,2192,1827,0
5,5,1aa498825382410b098937d65c4ec26d,6,8302,0,1998,796.94,1998,0.0,30.12,...,44.266930,0.000000,0.000000,44.430589,0.084587,0.000000,1,1827,1462,1423
6,6,7ab4bf4878d8f7661dfc20e9b8e18011,3,45097,0,0,8069.28,0,0.0,0.00,...,44.266930,0.000000,0.000000,44.430291,0.084305,0.000000,1,1827,1462,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14599,14599,c49217f16a06263e5381eaba94a67a8b,3,87146,0,11367,712.33,713,0.0,145.82,...,40.728885,24.437330,16.291555,40.852273,24.542485,16.368756,0,1095,731,0
14600,14600,18463073fb097fc0ac5d3e040f356987,3,32270,47940,0,4648.01,0,0.0,18.57,...,44.444710,0.000000,0.000000,44.584882,0.000000,0.000000,0,1445,732,1079
14601,14601,d0a6f71671571ed83b2645d23af6de00,3,7223,0,181,631.69,181,0.0,144.03,...,59.173468,36.490689,8.367731,59.275820,36.583870,8.438721,1,1461,1096,0
14602,14602,10e6828ddd62cbcf687cb74928c4c2d2,3,1844,0,179,190.39,179,0.0,129.60,...,40.728885,24.437330,16.291555,40.848791,24.539003,16.365274,1,1460,1097,0
14603,14603,1cf20fd6206d7678d5bcafd28c53b4db,3,131,0,0,19.34,0,0.0,7.18,...,44.444710,0.000000,0.000000,44.592310,0.000000,0.000000,0,1461,1096,0

In [209]:
price_df = pd.read_csv('price_data.csv')
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')
price_df.head()

,id,price_date,price_off_peak_var,price_peak_var,price_mid_peak_var,price_off_peak_fix,price_peak_fix,price_mid_peak_fix
0,038af19179925da21a25619c5a24b745,2015-01-01,0.151367,0.0,0.0,44.266931,0.0,0.0
1,038af19179925da21a25619c5a24b745,2015-02-01,0.151367,0.0,0.0,44.266931,0.0,0.0
2,038af19179925da21a25619c5a24b745,2015-03-01,0.151367,0.0,0.0,44.266931,0.0,0.0
3,038af19179925da21a25619c5a24b745,2015-04-01,0.149626,0.0,0.0,44.266931,0.0,0.0
4,038af19179925da21a25619c5a24b745,2015-05-01,0.149626,0.0,0.0,44.266931,0.0,0.0

In [210]:
monthly_price_by_id = price_df.groupby(['id', 'price_date']).agg({'price_off_peak_var': 'mean', 'price_off_peak_fix': 'mean'}).reset_index()
monthly_price_by_id.head(5)

,id,price_date,price_off_peak_var,price_off_peak_fix
0,0002203ffbb812588b632b9e628cc38d,2015-01-01,0.126098,40.565969
1,0002203ffbb812588b632b9e628cc38d,2015-02-01,0.126098,40.565969
2,0002203ffbb812588b632b9e628cc38d,2015-03-01,0.128067,40.728885
3,0002203ffbb812588b632b9e628cc38d,2015-04-01,0.128067,40.728885
4,0002203ffbb812588b632b9e628cc38d,2015-05-01,0.128067,40.728885

In [211]:
jan_prices = monthly_price_by_id.groupby('id').first().reset_index()
dec_prices = monthly_price_by_id.groupby('id').last().reset_index()

In [212]:
diff = pd.merge(dec_prices.rename(columns={'price_off_peak_var': 'dec_1', 'price_off_peak_fix': 'dec_2'}), jan_prices.drop(columns='price_date'), on='id')
diff['offpeak_diff_dec_january_energy'] = diff['dec_1'] - diff['price_off_peak_var']
diff['offpeak_diff_dec_january_power'] = diff['dec_2'] - diff['price_off_peak_fix']
diff = diff[['id', 'offpeak_diff_dec_january_energy','offpeak_diff_dec_january_power']]
diff.head()

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001

In [213]:
diff

,id,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0002203ffbb812588b632b9e628cc38d,-0.006192,0.162916
1,0004351ebdd665e6ee664792efc4fd13,-0.004104,0.177779
2,0010bcc39e42b3c2131ed2ce55246e3c,0.050443,1.500000
3,0010ee3855fdea87602a5b7aba8e42de,-0.010018,0.162916
4,00114d74e963e47177db89bc70108537,-0.003994,-0.000001
...,...,...,...
16091,ffef185810e44254c3a4c6395e6b4d8a,-0.050232,-0.335085
16092,fffac626da707b1b5ab11e8431a4d0a2,-0.003778,0.177779
16093,fffc0cacd305dd51f316424bbb08d1bd,-0.001760,0.164916
16094,fffe4f5646aa39c7f97f95ae2679ce64,-0.009391,0.162916
16095,ffff7fa066f1fb305ae285bb03bf325a,-0.009528,0.162916

In [214]:
client_data = pd.read_csv("client_data.csv")
client_data

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,t,0.00,25.44,25.44,2,678.99,3,lxidpiddsbxsbosboudacockeimpuepw,43.648,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,f,0.00,16.38,16.38,1,18.89,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.800,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,f,0.00,28.60,28.60,1,6.60,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.856,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,f,0.00,30.22,30.22,1,25.46,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,f,52.32,44.91,44.91,1,47.98,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,19.800,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14601,18463073fb097fc0ac5d3e040f356987,foosdfpfkusacimwkcsosbicdxkicaua,32270,47940,0,2012-05-24,2016-05-08,2015-05-08,2014-05-26,4648.01,...,t,0.00,27.88,27.88,2,381.77,4,lxidpiddsbxsbosboudacockeimpuepw,15.000,0
14602,d0a6f71671571ed83b2645d23af6de00,foosdfpfkusacimwkcsosbicdxkicaua,7223,0,181,2012-08-27,2016-08-27,2012-08-27,2015-08-28,631.69,...,f,15.94,0.00,0.00,1,90.34,3,lxidpiddsbxsbosboudacockeimpuepw,6.000,1
14603,10e6828ddd62cbcf687cb74928c4c2d2,foosdfpfkusacimwkcsosbicdxkicaua,1844,0,179,2012-02-08,2016-02-07,2012-02-08,2015-02-09,190.39,...,f,18.05,39.84,39.84,1,20.38,4,lxidpiddsbxsbosboudacockeimpuepw,15.935,1
14604,1cf20fd6206d7678d5bcafd28c53b4db,foosdfpfkusacimwkcsosbicdxkicaua,131,0,0,2012-08-30,2016-08-30,2012-08-30,2015-08-31,19.34,...,f,0.00,13.08,13.08,1,0.96,3,lxidpiddsbxsbosboudacockeimpuepw,11.000,0
14605,563dde550fd624d7352f3de77c0cdfcd,MISSING,8730,0,0,2009-12-18,2016-12-17,2009-12-18,2015-12-21,762.41,...,f,0.00,11.84,11.84,1,96.34,6,ldkssxwpmemidmecebumciepifcamkci,10.392,0

In [215]:
df1 = pd.merge(df,diff,on = 'id')

In [216]:
df1

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,...,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn,contract_duration,next_renewal,days_since_modif_prod,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,0,24011ae4ebbe3035111d65fa7c15bc57,3,0,54946,0,0.00,0,0.0,1.78,...,8.145777,42.629663,12.311304,8.182687,1,1096,738,869,0.020057,3.700961
1,2,764c75f661154dac3a6c254cd082ea7d,3,544,0,0,47.96,0,0.0,38.72,...,0.000000,44.612508,0.088409,0.000000,0,2192,1827,0,-0.004670,0.177779
2,3,bba03439a292a1e166f80264c16191cb,4,1584,0,0,240.04,0,0.0,19.83,...,0.000000,44.593296,0.000000,0.000000,0,2192,1827,0,-0.004547,0.177779
3,5,1aa498825382410b098937d65c4ec26d,6,8302,0,1998,796.94,1998,0.0,30.12,...,0.000000,44.430589,0.084587,0.000000,1,1827,1462,1423,-0.008087,-0.000001
4,6,7ab4bf4878d8f7661dfc20e9b8e18011,3,45097,0,0,8069.28,0,0.0,0.00,...,0.000000,44.430291,0.084305,0.000000,1,1827,1462,0,-0.004628,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10825,14599,c49217f16a06263e5381eaba94a67a8b,3,87146,0,11367,712.33,713,0.0,145.82,...,16.291555,40.852273,24.542485,16.368756,0,1095,731,0,-0.006756,0.162916
10826,14600,18463073fb097fc0ac5d3e040f356987,3,32270,47940,0,4648.01,0,0.0,18.57,...,0.000000,44.584882,0.000000,0.000000,0,1445,732,1079,-0.008653,0.177779
10827,14601,d0a6f71671571ed83b2645d23af6de00,3,7223,0,181,631.69,181,0.0,144.03,...,8.367731,59.275820,36.583870,8.438721,1,1461,1096,0,-0.007395,0.236694
10828,14602,10e6828ddd62cbcf687cb74928c4c2d2,3,1844,0,179,190.39,179,0.0,129.60,...,16.291555,40.848791,24.539003,16.365274,1,1460,1097,0,-0.006192,0.162916
10829,14603,1cf20fd6206d7678d5bcafd28c53b4db,3,131,0,0,19.34,0,0.0,7.18,...,0.000000,44.592310,0.000000,0.000000,0,1461,1096,0,-0.003767,0.177779

In [217]:
column_order = [col for col in df1.columns if col != 'churn'] + ['churn']
df1 = df1[column_order]

In [218]:
df1

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,...,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,contract_duration,next_renewal,days_since_modif_prod,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power,churn
0,0,24011ae4ebbe3035111d65fa7c15bc57,3,0,54946,0,0.00,0,0.0,1.78,...,8.145777,42.629663,12.311304,8.182687,1096,738,869,0.020057,3.700961,1
1,2,764c75f661154dac3a6c254cd082ea7d,3,544,0,0,47.96,0,0.0,38.72,...,0.000000,44.612508,0.088409,0.000000,2192,1827,0,-0.004670,0.177779,0
2,3,bba03439a292a1e166f80264c16191cb,4,1584,0,0,240.04,0,0.0,19.83,...,0.000000,44.593296,0.000000,0.000000,2192,1827,0,-0.004547,0.177779,0
3,5,1aa498825382410b098937d65c4ec26d,6,8302,0,1998,796.94,1998,0.0,30.12,...,0.000000,44.430589,0.084587,0.000000,1827,1462,1423,-0.008087,-0.000001,1
4,6,7ab4bf4878d8f7661dfc20e9b8e18011,3,45097,0,0,8069.28,0,0.0,0.00,...,0.000000,44.430291,0.084305,0.000000,1827,1462,0,-0.004628,0.000000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10825,14599,c49217f16a06263e5381eaba94a67a8b,3,87146,0,11367,712.33,713,0.0,145.82,...,16.291555,40.852273,24.542485,16.368756,1095,731,0,-0.006756,0.162916,0
10826,14600,18463073fb097fc0ac5d3e040f356987,3,32270,47940,0,4648.01,0,0.0,18.57,...,0.000000,44.584882,0.000000,0.000000,1445,732,1079,-0.008653,0.177779,0
10827,14601,d0a6f71671571ed83b2645d23af6de00,3,7223,0,181,631.69,181,0.0,144.03,...,8.367731,59.275820,36.583870,8.438721,1461,1096,0,-0.007395,0.236694,1
10828,14602,10e6828ddd62cbcf687cb74928c4c2d2,3,1844,0,179,190.39,179,0.0,129.60,...,16.291555,40.848791,24.539003,16.365274,1460,1097,0,-0.006192,0.162916,1
10829,14603,1cf20fd6206d7678d5bcafd28c53b4db,3,131,0,0,19.34,0,0.0,7.18,...,0.000000,44.592310,0.000000,0.000000,1461,1096,0,-0.003767,0.177779,0

In [219]:
df1 = df1.drop(columns=['id','Unnamed: 0'])

In [220]:
X = df1.iloc[:, :-1]
y = df1.iloc[:, -1:]

In [221]:
from sklearn.model_selection import train_test_split

# Assuming X is your feature matrix, y is your target variable
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [222]:
y_train = y_train.squeeze().ravel()
y_test = y_test.squeeze().ravel()

In [223]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
print(rf_classifier.get_params())

# Train the model

rf_classifier.fit(X_train, y_train)

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'sqrt', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': 42, 'verbose': 0, 'warm_start': False}

RandomForestClassifier(random_state=42)

In [224]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


y_pred = rf_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", classification_rep)

Accuracy: 0.9017

Confusion Matrix:
 [[1939    1]
 [ 212   14]]

Classification Report:
               precision    recall  f1-score   support

           0       0.90      1.00      0.95      1940
           1       0.93      0.06      0.12       226

    accuracy                           0.90      2166
   macro avg       0.92      0.53      0.53      2166
weighted avg       0.90      0.90      0.86      2166

In [225]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import make_scorer, precision_score, recall_score

# Assume you have your features X and target variable y
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a RandomForestClassifier
rf_classifier = RandomForestClassifier()

# Define the parameter grid to search
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Define the scoring metric (use 'precision' or 'recall' based on your business requirements)
scorer = make_scorer(recall_score)

# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, scoring=scorer, cv=3)

# Fit the model to the data
grid_search.fit(X_train, y_train)

# Get the best parameters and the corresponding model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the model on the test set
y_pred = best_model.predict(X_test)

# Print the best parameters
print("Best parameters:", best_params)

# Print the recall score on the test set
print("Recall on test set:", recall_score(y_test, y_pred))

Best parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Recall on test set: 0.06637168141592921

In [226]:
df

,Unnamed: 0,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,...,mean_3m_price_off_peak_fix,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,churn,contract_duration,next_renewal,days_since_modif_prod
0,0,24011ae4ebbe3035111d65fa7c15bc57,3,0,54946,0,0.00,0,0.0,1.78,...,42.497907,12.218665,8.145777,42.629663,12.311304,8.182687,1,1096,738,869
2,2,764c75f661154dac3a6c254cd082ea7d,3,544,0,0,47.96,0,0.0,38.72,...,44.444710,0.000000,0.000000,44.612508,0.088409,0.000000,0,2192,1827,0
3,3,bba03439a292a1e166f80264c16191cb,4,1584,0,0,240.04,0,0.0,19.83,...,44.444710,0.000000,0.000000,44.593296,0.000000,0.000000,0,2192,1827,0
5,5,1aa498825382410b098937d65c4ec26d,6,8302,0,1998,796.94,1998,0.0,30.12,...,44.266930,0.000000,0.000000,44.430589,0.084587,0.000000,1,1827,1462,1423
6,6,7ab4bf4878d8f7661dfc20e9b8e18011,3,45097,0,0,8069.28,0,0.0,0.00,...,44.266930,0.000000,0.000000,44.430291,0.084305,0.000000,1,1827,1462,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14599,14599,c49217f16a06263e5381eaba94a67a8b,3,87146,0,11367,712.33,713,0.0,145.82,...,40.728885,24.437330,16.291555,40.852273,24.542485,16.368756,0,1095,731,0
14600,14600,18463073fb097fc0ac5d3e040f356987,3,32270,47940,0,4648.01,0,0.0,18.57,...,44.444710,0.000000,0.000000,44.584882,0.000000,0.000000,0,1445,732,1079
14601,14601,d0a6f71671571ed83b2645d23af6de00,3,7223,0,181,631.69,181,0.0,144.03,...,59.173468,36.490689,8.367731,59.275820,36.583870,8.438721,1,1461,1096,0
14602,14602,10e6828ddd62cbcf687cb74928c4c2d2,3,1844,0,179,190.39,179,0.0,129.60,...,40.728885,24.437330,16.291555,40.848791,24.539003,16.365274,1,1460,1097,0
14603,14603,1cf20fd6206d7678d5bcafd28c53b4db,3,131,0,0,19.34,0,0.0,7.18,...,44.444710,0.000000,0.000000,44.592310,0.000000,0.000000,0,1461,1096,0

In [227]:
X

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,mean_3m_price_peak_fix,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,contract_duration,next_renewal,days_since_modif_prod,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power
0,3,0,54946,0,0.00,0,0.0,1.78,0.114481,0.098142,...,12.218665,8.145777,42.629663,12.311304,8.182687,1096,738,869,0.020057,3.700961
1,3,544,0,0,47.96,0,0.0,38.72,0.165794,0.087899,...,0.000000,0.000000,44.612508,0.088409,0.000000,2192,1827,0,-0.004670,0.177779
2,4,1584,0,0,240.04,0,0.0,19.83,0.146694,0.000000,...,0.000000,0.000000,44.593296,0.000000,0.000000,2192,1827,0,-0.004547,0.177779
3,6,8302,0,1998,796.94,1998,0.0,30.12,0.164775,0.086131,...,0.000000,0.000000,44.430589,0.084587,0.000000,1827,1462,1423,-0.008087,-0.000001
4,3,45097,0,0,8069.28,0,0.0,0.00,0.166178,0.087538,...,0.000000,0.000000,44.430291,0.084305,0.000000,1827,1462,0,-0.004628,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10825,3,87146,0,11367,712.33,713,0.0,145.82,0.120372,0.103487,...,24.437330,16.291555,40.852273,24.542485,16.368756,1095,731,0,-0.006756,0.162916
10826,3,32270,47940,0,4648.01,0,0.0,18.57,0.138305,0.000000,...,0.000000,0.000000,44.584882,0.000000,0.000000,1445,732,1079,-0.008653,0.177779
10827,3,7223,0,181,631.69,181,0.0,144.03,0.100167,0.091892,...,36.490689,8.367731,59.275820,36.583870,8.438721,1461,1096,0,-0.007395,0.236694
10828,3,1844,0,179,190.39,179,0.0,129.60,0.116900,0.100015,...,24.437330,16.291555,40.848791,24.539003,16.365274,1460,1097,0,-0.006192,0.162916
10829,3,131,0,0,19.34,0,0.0,7.18,0.145711,0.000000,...,0.000000,0.000000,44.592310,0.000000,0.000000,1461,1096,0,-0.003767,0.177779

In [228]:
from sklearn.preprocessing import StandardScaler

df1_numerical = df1.select_dtypes(include=['int64','float64'])
scaler = StandardScaler()

# Standardize each numerical column
df1[df1_numerical.columns] = scaler.fit_transform(df1[df1_numerical.columns])
df1

,channel_sales,cons_12m,cons_gas_12m,cons_last_month,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_off_peak,forecast_price_energy_peak,...,mean_3m_price_mid_peak_fix,mean_3m_price_off_peak,mean_3m_price_peak,mean_3m_price_mid_peak,contract_duration,next_renewal,days_since_modif_prod,offpeak_diff_dec_january_energy,offpeak_diff_dec_january_power,churn
0,-0.315716,-0.285897,0.155613,-0.256803,-0.803585,-0.486918,-0.200481,-0.931793,-1.044670,0.976563,...,0.247658,-0.235757,0.237428,0.247551,-1.608891,-1.559962,0.318009,1.950262,2.469471,2.926967
1,-0.315716,-0.285009,-0.167215,-0.256803,-0.783413,-0.486918,-0.200481,-0.368403,1.199238,0.769086,...,-0.785789,0.430929,-0.780021,-0.785821,0.868218,0.877513,-0.901282,-0.009288,-0.068148,-0.341651
2,0.502667,-0.283312,-0.167215,-0.256803,-0.702624,-0.486918,-0.200481,-0.656503,0.363998,-1.011356,...,-0.785789,0.424469,-0.787380,-0.785821,0.868218,0.877513,-0.901282,0.000460,-0.068148,-0.341651
3,2.139432,-0.272352,-0.167215,-0.227498,-0.468392,0.211875,-0.200481,-0.499565,1.154677,0.733274,...,-0.785789,0.369763,-0.780339,-0.785821,0.043269,0.060545,1.095325,-0.280076,-0.196197,2.926967
4,-0.315716,-0.212323,-0.167215,-0.256803,2.590352,-0.486918,-0.200481,-0.958940,1.216030,0.761774,...,-0.785789,0.369662,-0.780362,-0.785821,0.043269,0.060545,-0.901282,-0.005960,-0.196196,2.926967
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10825,-0.315716,-0.143722,-0.167215,-0.090079,-0.503979,-0.237549,-0.200481,1.265032,-0.787058,1.084829,...,1.281105,-0.833363,1.255566,1.281351,-1.611151,-1.575630,-0.901282,-0.174598,-0.078854,-0.341651
10826,-0.315716,-0.233250,0.114450,-0.256803,1.151367,-0.486918,-0.200481,-0.675720,-0.002851,-1.011356,...,-0.785789,0.421640,-0.787380,-0.785821,-0.820103,-1.573391,0.612660,-0.324930,-0.068148,-0.341651
10827,-0.315716,-0.274113,-0.167215,-0.254149,-0.537896,-0.423614,-0.200481,1.237732,-1.670618,0.849966,...,0.275817,5.361126,2.257906,0.279885,-0.783941,-0.758662,-0.901282,-0.225237,-0.025714,2.926967
10828,-0.315716,-0.282888,-0.167215,-0.254178,-0.723507,-0.424314,-0.200481,1.017653,-0.938888,1.014502,...,1.281105,-0.834533,1.255277,1.280911,-0.786201,-0.756423,-0.901282,-0.129902,-0.078854,2.926967
10829,-0.315716,-0.285683,-0.167215,-0.256803,-0.795451,-0.486918,-0.200481,-0.849435,0.321012,-1.011356,...,-0.785789,0.424138,-0.787380,-0.785821,-0.783941,-0.758662,-0.901282,0.062272,-0.068148,-0.341651

In [229]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import make_scorer, precision_score, recall_score

# Assume you have your features X and target variable y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train = y_train.squeeze().ravel()
y_test = y_test.squeeze().ravel()

# Create a RandomForestClassifier
rf_classifier = RandomForestClassifier()

# Define the parameter grid to search
param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Define the scoring metric (use 'precision' or 'recall' based on your business requirements)
scorer = make_scorer(recall_score)

# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=rf_classifier, param_grid=param_grid, scoring=scorer, cv=3)

# Fit the model to the data
grid_search.fit(X_train, y_train)

# Get the best parameters and the corresponding model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_

# Evaluate the model on the test set
y_pred = best_model.predict(X_test)

# Print the best parameters
print("Best parameters:", best_params)

# Print the recall score on the test set
print("Recall on test set:", recall_score(y_test, y_pred))

Best parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 50}
Recall on test set: 0.04524886877828054